site_name: ""
site_url: https://avolkha.github.io/home/
theme:
  name: material
  features:
      - navigation.footer  # optional, but keep if you use custom footers
  palette:
    primary: white
draft_docs: |
  - ./drafts
plugins:
  - blog:
      blog_dir: ./blog/
      authors: true
      authors_file: ".authors.yml"
  - rss:
      match_path: posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
extra_css:
  - styles/extra.css

